# Generated by Django 5.2.8 on 2025-11-25 16:41

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('text', tinymce.models.HTMLField(blank=True, editable=False, null=True, verbose_name='Текст')),
                ('phone', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Телефон')),
                ('phone_dop', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Телефон (дополнительный)')),
                ('fax', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Факс')),
                ('address', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Адрес')),
                ('email', models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='Электронная почта')),
                ('rezhim', models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='Режим работы')),
                ('comment', models.CharField(editable=False, max_length=256, verbose_name='Заголовок контактов')),
                ('text_head', models.TextField(blank=True, null=True, verbose_name='Блок в head (внизу)')),
                ('text_body', models.TextField(blank=True, null=True, verbose_name='Блок в body (внизу)')),
                ('link_twitter', models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='Ссылка на twitter')),
                ('link_facebook', models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='Ссылка на facebook')),
                ('link_lj', models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='Ссылка на lj')),
                ('link_instagram', models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='Ссылка на instagram')),
                ('link_vk', models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='Ссылка на вконтакте')),
            ],
            options={
                'verbose_name_plural': 'Счетчики Яндекс и другие',
                'db_table': 'contacts_contacts',
                'ordering': ['id'],
            },
        ),
    ]
