# Generated by Django 5.2.8 on 2025-11-25 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
                ('name_lat', models.CharField(blank=True, max_length=1024, verbose_name='Название латинское')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка')),
                ('isCvetMet', models.BooleanField(blank=True, db_column='iscvetmet', verbose_name='Цветной металл?')),
                ('isHidden', models.BooleanField(blank=True, db_column='ishidden', verbose_name='Скрыть')),
            ],
            options={
                'verbose_name_plural': 'Металл (верхний уровень)',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='MetallGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
                ('name_lat', models.CharField(blank=True, max_length=1024, verbose_name='Название латинское')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('isHidden', models.BooleanField(blank=True, db_column='ishidden', verbose_name='Скрыть')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marochnik.metall', verbose_name='Металл')),
            ],
            options={
                'verbose_name_plural': 'Разновидности металла (средний уровень)',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='MarkaMetall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
                ('name_lat', models.CharField(blank=True, max_length=1024, verbose_name='Название латинское')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('isHidden', models.BooleanField(blank=True, db_column='ishidden', verbose_name='Скрыть')),
                ('hiddenSite', models.BooleanField(blank=True, db_column='hiddensite', default=False, verbose_name='Скрыть из листингов')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marochnik.metallgroup', verbose_name='Разновидность металла')),
            ],
            options={
                'verbose_name_plural': 'Марка металла (нижний уровень)',
                'db_table': 'marochnik_markametall',
                'ordering': ['name'],
            },
        ),
    ]
