# Generated by Django 5.2.8 on 2025-11-25 16:41

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Типы новостей/статей',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
                ('name_lat', models.CharField(blank=True, max_length=1024, verbose_name='Название латинское')),
                ('articles_flag', models.BooleanField(blank=True, verbose_name='Флаг - статьей')),
                ('nameLatCat_1', models.CharField(blank=True, db_column='namelatcat_1', max_length=1024, null=True, verbose_name='Название лат. каталога статьи')),
                ('nameLatCat_2', models.CharField(blank=True, db_column='namelatcat_2', max_length=1024, null=True, verbose_name='Название лат. каталога статьи')),
                ('nameLatProd_1', models.CharField(blank=True, db_column='namelatprod_1', max_length=1024, null=True, verbose_name='Название лат. продукта статьи')),
                ('nameLatProd_2', models.CharField(blank=True, db_column='namelatprod_2', max_length=1024, null=True, verbose_name='Название лат. продукта статьи')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('title_main', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Заголовок страницы')),
                ('keywords', models.TextField(blank=True, help_text='Ключевые слова для SEO продвижения (через запятую). Мета тэг - keywords', null=True, verbose_name='Ключевые слова (мета)')),
                ('keywords_description', models.TextField(blank=True, help_text='Содержимое мета тэга - description', null=True, verbose_name='Описание (мета)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка новости')),
                ('isMain', models.BooleanField(db_column='ismain', verbose_name='Показывать в нижней панели')),
                ('isHidden', models.BooleanField(blank=True, db_column='ishidden', verbose_name='Скрыть')),
                ('video', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Видео на Youtube')),
                ('isHiddenVideo', models.BooleanField(blank=True, db_column='ishiddenvideo', verbose_name='Не показывать видео')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='News.newstype', verbose_name='Тип новости/статьи')),
            ],
            options={
                'verbose_name_plural': 'Новости/статьи',
                'db_table': 'news_news',
                'ordering': ['-date'],
            },
        ),
    ]
