# Generated by Django 5.2.8 on 2025-12-01 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0004_alter_menucatalog_catalog_childs_dop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogFilterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
                ('name_lat', models.CharField(blank=True, max_length=1024, verbose_name='Название латинское')),
                ('is_hidden', models.BooleanField(blank=True, verbose_name='Скрыть')),
            ],
            options={
                'verbose_name_plural': 'Фильтры',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='CatalogFilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('value', models.CharField(max_length=1024, verbose_name='Значение параметра')),
                ('value_lat', models.CharField(blank=True, max_length=1024, verbose_name='Значение параметра латинское')),
                ('is_hidden', models.BooleanField(blank=True, verbose_name='Скрыть')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menucatalog', verbose_name='Название категории')),
                ('filter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_filter.catalogfiltername', verbose_name='Название фильтра')),
            ],
            options={
                'verbose_name_plural': 'Значения фильтров',
                'ordering': ['order_number'],
            },
        ),
    ]
