# Generated by Django 5.2.8 on 2025-12-01 11:44

from django.db import migrations
import re
from transliterate import translit

def fix_slugs(apps, schema_editor):
    """
    Parcourt toutes les CatalogFilterValue et régénère leur value_lat.
    """
    CatalogFilterValue = apps.get_model('catalog_filter', 'CatalogFilterValue')
    for item in CatalogFilterValue.objects.all():
        if item.value:
            value_for_slug = str(item.value).replace(',', '.')
            slug_base = translit(value_for_slug, "ru", reversed=True)
            slug = re.sub(r'[^a-z0-9]+', '-', slug_base.lower()).strip('-')
            
            if item.value_lat != slug:
                item.value_lat = slug
                item.save(update_fields=['value_lat'])

class Migration(migrations.Migration):

    dependencies = [
        ('catalog_filter', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_slugs, reverse_code=migrations.RunPython.noop),
    ]