# Generated by Django 5.2.8 on 2025-11-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=1024, verbose_name='Латинское название [системное]')),
                ('text', models.TextField(blank=True, null=True, verbose_name='HTML текст')),
                ('template', models.FileField(blank=True, default='', editable=False, null=True, upload_to='uploads/templates', verbose_name='Файл HTML шаблона')),
                ('comment', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Статические тексты',
                'ordering': ['id'],
            },
        ),
    ]
