# Generated by Django 5.2.8 on 2025-11-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название компании')),
                ('site_name', models.CharField(max_length=256, verbose_name='Название сайта')),
                ('text_head', models.TextField(blank=True, default='', editable=False, null=True, verbose_name='Блок в head (внизу)')),
                ('text_body', models.TextField(blank=True, default='', editable=False, null=True, verbose_name='Блок в body (внизу)')),
                ('tech_mail_server', models.CharField(blank=True, default='', editable=False, max_length=256, null=True, verbose_name='Почтовый сервер (для отправки сообщений)')),
                ('tech_email', models.CharField(blank=True, default='', editable=False, max_length=256, null=True, verbose_name='Почта для отправки сообщений')),
                ('tech_email_pass', models.CharField(blank=True, default='', editable=False, max_length=256, null=True, verbose_name='Пароль почты для отправки сообщений')),
            ],
            options={
                'verbose_name_plural': 'Настройки проекта',
                'ordering': ['id'],
            },
        ),
    ]
