# Generated by Django 5.2.8 on 2025-11-25 16:41

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
                ('name_p', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название (в предложеном падеже)')),
                ('subdomain_name', models.CharField(max_length=1024, verbose_name='Название поддомена')),
                ('phone', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Телефон')),
                ('phone_yclid', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Телефон (yclid)')),
                ('phone_gclid', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Телефон (gclid)')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name='Электронная почта')),
                ('email_yclid', models.CharField(blank=True, max_length=256, null=True, verbose_name='Электронная почта (yclid)')),
                ('email_gclid', models.CharField(blank=True, max_length=256, null=True, verbose_name='Электронная почта (gclid)')),
                ('phone_dop', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Телефон (дополнительный)')),
                ('fax', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Факс')),
                ('address', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Адрес')),
                ('rezhim', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Режим работы')),
                ('req', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Реквизиты')),
                ('comment', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/images', verbose_name='Картинка')),
                ('is_main', models.BooleanField(blank=True, verbose_name='Отображается без поддомена (по умолчанию)')),
                ('isHidden', models.BooleanField(blank=True, db_column='ishidden', verbose_name='Скрыть')),
                ('geo', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Код карты')),
                ('text_head_filial', models.TextField(blank=True, default='', null=True, verbose_name='Блок в head для филиала (внизу)')),
                ('text_body_filial', models.TextField(blank=True, default='', null=True, verbose_name='Блок в body для филиала (внизу)')),
            ],
            options={
                'verbose_name_plural': 'Филиалы (Города)',
                'db_table': 'filials_filials',
                'ordering': ['name'],
            },
        ),
    ]
