# Generated by Django 5.2.8 on 2025-11-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('text', models.CharField(blank=True, max_length=256, null=True, verbose_name='Текст')),
                ('text_more', models.CharField(blank=True, max_length=256, null=True, verbose_name='Текст дополнительно')),
                ('string_down', models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='Текст дополнительный')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='uploads/images', verbose_name='Картинка')),
                ('isHidden', models.BooleanField(blank=True, db_column='ishidden', verbose_name='Скрыть')),
            ],
            options={
                'verbose_name_plural': 'Слайдер',
                'ordering': ['order_number'],
            },
        ),
    ]
