# Generated by Django 5.2.8 on 2025-11-25 16:41

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GOST', '__first__'),
        ('Marochnik', '0001_initial'),
        ('Sertificats', '__first__'),
        ('typemenu', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название пункта')),
                ('name_short', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название пункта (сокращенное)')),
                ('name_p', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название пункта (в винительном падеже)')),
                ('slug', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Название латинское')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('name_title', models.CharField(blank=True, max_length=1024, verbose_name='Название (в ед. числе)')),
                ('name_info', models.CharField(blank=True, max_length=1024, verbose_name='Название (для поля консультация)')),
                ('price_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок поля цена')),
                ('parent_catalog_dop', models.BooleanField(blank=True, verbose_name='Родительская категория для вложенных (дополнительных)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка')),
                ('labelSizeA', models.CharField(blank=True, db_column='labelsizea', max_length=256, null=True, verbose_name='Название размера А')),
                ('labelSizeAslug', models.CharField(blank=True, db_column='labelsizeaslug', max_length=256, null=True, verbose_name='Название размера А для фильтра (транслит)')),
                ('labelSizeB', models.CharField(blank=True, db_column='labelsizeb', max_length=256, null=True, verbose_name='Название размера B')),
                ('labelSizeBslug', models.CharField(blank=True, db_column='labelsizebslug', max_length=256, null=True, verbose_name='Название размера B для фильтра (транслит)')),
                ('labelSizeC', models.CharField(blank=True, db_column='labelsizec', max_length=256, null=True, verbose_name='Название размера C')),
                ('labelSizeCslug', models.CharField(blank=True, db_column='labelsizecslug', max_length=256, null=True, verbose_name='Название размера C для фильтра (транслит)')),
                ('labelSizeD', models.CharField(blank=True, db_column='labelsized', max_length=256, null=True, verbose_name='Название размера D')),
                ('labelSizeDslug', models.CharField(blank=True, db_column='labelsizedslug', max_length=256, null=True, verbose_name='Название размера D для фильтра (транслит)')),
                ('labelSizeE', models.CharField(blank=True, db_column='labelsizee', max_length=256, null=True, verbose_name='Название размера E')),
                ('labelSizeEslug', models.CharField(blank=True, db_column='labelsizeeslug', max_length=256, null=True, verbose_name='Название размера E для фильтра (транслит)')),
                ('labelSizeF', models.CharField(blank=True, db_column='labelsizef', max_length=256, null=True, verbose_name='Название размера F')),
                ('labelSizeFslug', models.CharField(blank=True, db_column='labelsizefslug', max_length=256, null=True, verbose_name='Название размера F для фильтра (транслит)')),
                ('labelSizeL', models.CharField(blank=True, db_column='labelsizel', max_length=256, null=True, verbose_name='Название размера L')),
                ('labelSizeLslug', models.CharField(blank=True, db_column='labelsizelslug', max_length=256, null=True, verbose_name='Название размера L для фильтра (транслит)')),
                ('isHideMarka', models.BooleanField(blank=True, db_column='ishidemarka', verbose_name='Скрыть марку')),
                ('isHideGOST', models.BooleanField(blank=True, db_column='ishidegost', verbose_name='Скрыть ГОСТ')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('oplata', models.TextField(blank=True, null=True, verbose_name='Текст Оплата и отгрузка / блок head для меню с типом Информация')),
                ('dostavka', models.TextField(blank=True, null=True, verbose_name='Текст Доставка/ блок body для меню с типом Информация')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Комментарий')),
                ('flagFooter', models.BooleanField(db_column='flagfooter', verbose_name='Флаг Footer')),
                ('flagProduct', models.BooleanField(db_column='flagproduct', default=False, verbose_name='Выводим товары под текстом ?')),
                ('title_main', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Заголовок страницы')),
                ('keywords', models.TextField(blank=True, help_text='Ключевые слова для SEO продвижения (через запятую). Мета тэг - keywords', null=True, verbose_name='Ключевые слова (мета)')),
                ('keywords_description', models.TextField(blank=True, help_text='Содержимое мета тэга - description', null=True, verbose_name='Описание (мета)')),
                ('isHidden', models.BooleanField(blank=True, db_column='ishidden', verbose_name='Скрыть')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_childs_dop', models.ManyToManyField(blank=True, to='menu.menucatalog', verbose_name='Вложенные категории (дополнительные)')),
                ('catalog_childs_dop_menu', models.ManyToManyField(blank=True, to='menu.menucatalog', verbose_name='Вложенные категории (дополнительные в меню)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menucatalog', verbose_name='Родительский пункт')),
                ('typeMenu', models.ForeignKey(db_column='typemenu_id', on_delete=django.db.models.deletion.PROTECT, to='typemenu.typemenu', verbose_name='Тип меню')),
            ],
            options={
                'verbose_name_plural': 'Меню/Каталог',
                'ordering': ['-order_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Приоритет (Порядковый номер)')),
                ('name_main', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название')),
                ('name_info', models.CharField(blank=True, max_length=1024, verbose_name="Название (для поля консультация разделов 'Производство','Услуги','Спецпредложения')")),
                ('slug', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название латинское')),
                ('size_a', models.CharField(blank=True, max_length=256, null=True, verbose_name='Размер A')),
                ('size_b', models.CharField(blank=True, max_length=256, null=True, verbose_name='Размер B')),
                ('size_c', models.CharField(blank=True, max_length=256, null=True, verbose_name='Размер C')),
                ('size_d', models.CharField(blank=True, max_length=256, null=True, verbose_name='Размер D')),
                ('size_e', models.CharField(blank=True, max_length=256, null=True, verbose_name='Размер E')),
                ('size_f', models.CharField(blank=True, max_length=256, null=True, verbose_name='Размер F')),
                ('size_l', models.CharField(blank=True, max_length=256, null=True, verbose_name='Размер L')),
                ('available', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наличие')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('ed_izm', models.CharField(blank=True, max_length=256, null=True, verbose_name='Единицы измерения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка')),
                ('image_dop', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка (дополнительная)')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('vendor', models.CharField(blank=True, max_length=256, null=True, verbose_name='Производитель')),
                ('vendor_country', models.CharField(blank=True, max_length=256, null=True, verbose_name='Страна производителя')),
                ('method_of_manufacture', models.CharField(blank=True, max_length=256, null=True, verbose_name='Способ изготовления')),
                ('title_main', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Заголовок страницы')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова (мета)')),
                ('keywords_description', models.TextField(blank=True, null=True, verbose_name='Описание (мета)')),
                ('isHidden', models.BooleanField(blank=True, db_column='ishidden', verbose_name='Скрыть')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menucatalog', verbose_name='Категория металлопроката')),
                ('catalogOne', models.ForeignKey(blank=True, db_column='catalogone_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_catalogOne', to='menu.menucatalog', verbose_name='Категория металлопроката 1')),
                ('catalogThree', models.ForeignKey(blank=True, db_column='catalogthree_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_catalogThree', to='menu.menucatalog', verbose_name='Категория металлопроката 3')),
                ('catalogTwo', models.ForeignKey(blank=True, db_column='catalogtwo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_catalogTwo', to='menu.menucatalog', verbose_name='Категория металлопроката 2')),
                ('gost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOST.gost', verbose_name='ГОСТ')),
                ('marka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Marochnik.markametall', verbose_name='Марка')),
                ('sertificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sertificats.sertificats', verbose_name='Сертификат')),
            ],
            options={
                'verbose_name_plural': 'Продукт',
                'ordering': ['-order_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductUsluga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isHidden', models.BooleanField(blank=True, db_column='ishidden', verbose_name='Скрыть')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product', verbose_name='Продукт')),
                ('usluga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menucatalog', verbose_name='Услуга')),
            ],
            options={
                'verbose_name_plural': 'Продукт - Услуга',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tableProductDop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isHidden', models.BooleanField(blank=True, db_column='ishidden', verbose_name='Скрыть')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='menu.product', verbose_name='Продукт')),
                ('product_dop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_dop', to='menu.product', verbose_name='Дополнительный продукт')),
            ],
            options={
                'verbose_name_plural': 'Таблица дополнительных продуктов',
                'ordering': ['id'],
            },
        ),
    ]
