# Generated by Django 5.2.8 on 2025-11-29 18:02

# import django.db.models.functions.text
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('GOST', '__first__'),
#         ('Marochnik', '0001_initial'),
#         ('Sertificats', '__first__'),
#         ('menu', '0001_initial'),
#         ('typemenu', '__first__'),
#     ]

#     operations = [
#         migrations.AddIndex(
#             model_name='menucatalog',
#             index=models.Index(django.db.models.functions.text.Upper('slug'), name='menucatalog_slug_upper_idx'),
#         ),
#         migrations.AddIndex(
#             model_name='product',
#             index=models.Index(django.db.models.functions.text.Upper('slug'), name='product_slug_upper_idx'),
#         ),
#         migrations.AlterModelTable(
#             name='menucatalog',
#             table='menu_menucatalog',
#         ),
#     ]


from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('GOST', '__first__'),
        ('Marochnik', '0001_initial'),
        ('Sertificats', '__first__'),
        ('menu', '0001_initial'),
        ('typemenu', '__first__'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_menu_product_slug_upper_text 
                ON menu_product (UPPER(slug::text));
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_menu_product_slug_upper_text;
            """
        ),

        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_menu_menucatalog_slug_upper_text 
                ON menu_menucatalog (UPPER(slug::text));
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_menu_menucatalog_slug_upper_text;
            """
        ),
        migrations.AlterModelTable(
            name='menucatalog',
            table='menu_menucatalog',
        ),
    ]