# Generated by Django 5.2.8 on 2025-11-29 18:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOST', '__first__'),
        ('Marochnik', '0001_initial'),
        ('Sertificats', '__first__'),
        ('menu', '0002_menucatalog_menucatalog_slug_upper_idx_and_more'),
        ('typemenu', '__first__'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menucatalog',
            index=models.Index(django.db.models.functions.text.Upper('slug'), name='menucatalog_slug_upper_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(django.db.models.functions.text.Upper('slug'), name='product_slug_upper_idx'),
        ),
    ]
