# Generated by Django 5.2.8 on 2025-11-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menucatalog_menucatalog_slug_upper_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucatalog',
            name='catalog_childs_dop',
            field=models.ManyToManyField(blank=True, related_name='parent_catalogs_dop', to='menu.menucatalog', verbose_name='Вложенные категории (дополнительные)'),
        ),
        migrations.AlterField(
            model_name='menucatalog',
            name='catalog_childs_dop_menu',
            field=models.ManyToManyField(blank=True, related_name='parent_catalogs_dop_menu', to='menu.menucatalog', verbose_name='Вложенные категории (дополнительные в меню)'),
        ),
    ]
