# Generated by Django 5.2.8 on 2025-11-25 16:41

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Filials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlockUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, verbose_name='url страницы')),
                ('order_number', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('text', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка')),
                ('title_main', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Заголовок страницы')),
                ('keywords', models.TextField(blank=True, help_text='Ключевые слова для SEO продвижения (через запятую). Мета тэг - keywords', null=True, verbose_name='Ключевые слова (мета)')),
                ('keywords_description', models.TextField(blank=True, help_text='Содержимое мета тэга - description', null=True, verbose_name='Описание (мета)')),
                ('isHidden', models.BooleanField(blank=True, db_column='ishidden', verbose_name='Скрыть')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Filials.filials', verbose_name='Регион показа')),
            ],
            options={
                'verbose_name_plural': 'Текстовый блок (ссылка)',
                'db_table': 'textblockurl_textblockurl',
                'ordering': ['order_number'],
            },
        ),
    ]
